site_name: JustTweenIt
nav:
    - Overview: index.md
    - Basic concepts: BasicConcepts.md
    - BuiltIn animations: BuiltInAnimations.md
    - Create user custom animations: CreateUserCustomAnimation.md
    - Unit Tests: UnitTests.md
theme:
  name: readthedocs
markdown_extensions:
  - codehilite:
      linenums: true
