site_name: JustTweenIt
nav:
    - Overview: index.md
    - Basic concepts: BasicConcepts.md
    - BuiltIn animations: BuiltInAnimations.md
    - Create user custom animations: CreateUserCustomAnimation.md
    - Unit Tests: UnitTests.md
copyright: Copyright © 2020 - 2020 Aleksey Diudia
site_author: Aleksey Diudia
theme:
  name: material
  palette:
    scheme: slate
    primary: amber
    accent: indigo
google_analytics: ['UA-174990548-1', 'etlay.github.io/JustTweenItDocs/']
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
